services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./back/.env.test

  api:
    container_name: api
    build: ./back
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - ./back/.env