name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_PORT: 4000
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "root"
          envkey_POSTGRES_DB: "annyong"
          envkey_DATABASE_URL: "postgresql://postgres:root@postgres:5433/annyong"
          directory: back
          file_name: .env
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node npm run test